version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          command: npm test
